def wrap_with_full_template(fragments):
    """
    将所有译文片段组装成完整的 LaTeX 文档
    """
    # 按照页面和 ID 排序，确保逻辑顺序正确
    sorted_frags = sorted(fragments, key=lambda x: (x.get('page', 0), x.get('id', '')))
    
    content = "\n\n".join([f["content"] for f in sorted_frags])
    
    template = r"""
\documentclass[11pt,a4paper]{article}
\usepackage[UTF8]{xeCJK}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{geometry}
\usepackage{hyperref}
\geometry{left=2.5cm,right=2.5cm,top=3cm,bottom=3cm}

\title{PaperLean 数学文献译本}
\author{Generated by PaperLean Agent}
\date{\today}

\begin{document}
\maketitle

% --- 正文开始 ---
""" + content + r"""
% --- 正文结束 ---

\end{document}
"""
    return template